apiVersion: v1
kind: Pod
metadata:
    name: httpd
spec:
    containers:
    - name: httpd
      image: registry.access.redhat.com/ubi8/httpd-24
      ports:
      - name: http
        containerPort: 8080
      volumeMounts:
      - name: docroot
        mountPath: /var/www/html
        readOnly: true
    volumes:
    - name: docroot
      configMap:
        name: httpd-index