apiVersion: v1
kind: Secret
metadata:
    name: postgres-config
    namespace: httpd-dev
data:
    POSTGRESQL_USERNAME: bXlkYXRhYmFzZV91c2Vy
    POSTGRESQL_PASSWORD: cjNkaDR0MSE=
    POSTGRESQL_DATABASE: bXlkYXRhYmFzZQ==