apiVersion: v1
kind: Namespace
metadata:
  name: omc
spec: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: omc-sa
  namespace: omc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: omc-sa-role
  namespace: omc
rules:
  - apiGroups:
      - "*"
    resources:
      - clusterversions
      - infrastructures
      - machinesets
      - nodes
      - routes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: omc-sa-rolebinding
  namespace: omc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: omc-sa-role
subjects:
  - kind: ServiceAccount
    name: omc-sa
    namespace: omc