apiVersion: v1
kind: Pod
metadata:
  name: best-effort
  namespace: requests-limits
spec:
  containers:
  - name: ubi
    image: registry.access.redhat.com/ubi8/ubi-minimal
    command: 
    - "sleep"
    args:
    - "infinity"
