apiVersion: v1
kind: Pod
metadata:
  name: burstable-2
  namespace: requests-limits
spec:
  containers:
  - name: ubi
    image: registry.access.redhat.com/ubi8/ubi-minimal
    command: 
    - "sleep"
    args:
    - "infinity"
    resources:
      requests:
        cpu: "0.1"
        memory: "64Mi"
      limits:
        cpu: "0.2"
        memory: "128Mi"